-- Generated by lampe

import Examples.Extracted.Fib
import Examples.Extracted.GeneratedTypes
import Examples.Extracted.Generics
import Examples.Extracted.Lib
import Examples.Extracted.Unconst

def Extracted.env := Extracted.Fib.env ++ Extracted.Generics.env ++ Extracted.Lib.env ++ Extracted.Unconst.env