-- Generated by lampe

import Examples.Extracted.GeneratedTypes
import Lampe

open Lampe

namespace Extracted

nr_def «fib»::«fib»<@N : u32>() -> Field {
    let mut a = 0 : Field;
    let mut b = 1 : Field;
    for _? in 0 : u32 .. u@N {
            let temp = a;
        a = b;
        b = #fAdd(temp, b) : Field;
        skip;
    };
    a;
}


def Fib.env := Lampe.Env.mk [«fib::fib»] []