-- Generated by lampe

import Examples.Extracted.GeneratedTypes
import Lampe

open Lampe

namespace Extracted

nr_trait_impl[impl_405] <I, I> generics::HasFirst<I> for generics::Pairs<I> where  {
    fn «generics»::«first»<> (self : generics::Pairs<I>) -> I {
        (self as generics::Pairs<I>).a;
}
}


def Generics.env := Lampe.Env.mk [] [impl_405]