-- Generated by lampe

import Examples.Extracted.GeneratedTypes
import Lampe

open Lampe

namespace Extracted

nr_def «simple»<>(x : Field) -> Field {
    let mut y = x;
    y = #fAdd(y, 1 : Field) : Field;
    y = #fMul(y, x) : Field;
    y;
}


def Lib.env := Lampe.Env.mk [«simple»] []