-- Generated by lampe

import Examples.Extracted.GeneratedTypes
import Lampe

open Lampe

namespace Extracted

nr_def «unconst»::«new»<>() -> Field {
    #fresh() : Field
}

nr_def «unconst»::«test»<>() -> Unit {
    let x =     3 : Field;
    let y = (@unconst::new<> as λ() → Field)();
    #assert(#fEq(x, y) : bool) : Unit;
    skip;
}


def Unconst.env := Lampe.Env.mk [«unconst::new», «unconst::test»] []